### ISSUE TITLE
ModuleNotFoundError: No module named 'libnmap'

### ISSUE THREAD

**Issue by TheSidd** [woj-ciech/Kamerka-GUI#13]
I ran the first command after requirements.txt and below is the error.

`python3 manage.py makemigrations`

`
kali@kali:~/Desktop/Kamerka-GUI$ python3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/kali/.local/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/kali/.local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kali/.local/lib/python3.7/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kali/.local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kali/.local/lib/python3.7/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kali/Desktop/Kamerka-GUI/kamerka/urls.py", line 21, in <module>
    path('', include('app_kamerka.urls'),
  File "/home/kali/.local/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kali/Desktop/Kamerka-GUI/app_kamerka/urls.py", line 2, in <module>
    from app_kamerka import views
  File "/home/kali/Desktop/Kamerka-GUI/app_kamerka/views.py", line 18, in <module>
    from kamerka.tasks import bosch_usernames,shodan_search, devices_nearby, twitter_nearby_task, flickr, shodan_scan_task, \
  File "/home/kali/Desktop/Kamerka-GUI/kamerka/tasks.py", line 5, in <module>
    from libnmap.parser import NmapParser
ModuleNotFoundError: No module named 'libnmap'
kali@kali:~/Desktop/Kamerka-GUI$
`

**Comment by TheSidd** [comment]
Using `python` gave me below error

![image](https://user-images.githubusercontent.com/16534440/76332758-cabc7480-6316-11ea-8d87-c0d93c0e2c1d.png)

**Comment by woj-ciech** [comment]
I forgot to add library for NMAP.
sudo pip3 install python-libnmap
https://github.com/woj-ciech/Kamerka-GUI/commit/bcac466b200e4144574d8c65aeb962806cfad496
